### ISSUE TITLE
Prevent slideshow from opening by default

### ISSUE THREAD

**Issue by r3ck3z57** [KitchenStories/vue-gallery-slideshow#10]
Hello,
First off, thank you for making this! The slideshow works great, but I was wondering if there was a way to not open it as soon as the page loads and only open it when an image is clicked on.

Great job and please let me know.

**Comment by headione** [comment]
Hi, please ensure that the initial value of index is null and the gallery will not open.

**Comment by r3ck3z57** [comment]
Thank you!
