### ISSUE TITLE
IE11 - Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by cleptric** [KitchenStories/vue-gallery-slideshow#11]
The transpiled `vue-gallery-slideshow.js` file contains a usage of `includes`, which isn't supported by IE11.
`if (!style.ids.includes(id)) {...`
Regarding to the .babelrc, it should not use this method.

**Comment by matkovsky** [comment]
Also, there is an arrow function in the dist code, which breaks in IE11. 😭 

![image](https://user-images.githubusercontent.com/1693178/51389048-77440180-1b2b-11e9-8d3c-985296c9e692.png)

**Comment by barnabas-szekeres** [comment]
Same issue here! :(

**Comment by iamqqv** [comment]
@matkovsky your fix fixes that arrow function issue. thank you!

**Comment by headione** [comment]
ok, I'll change this in the coming release. Thanks @matkovsky for this hint and @iamqqv for validation of this fix 👍 <3

**Comment by iamqqv** [comment]
cool, thank you. any idea about this `includes` error? maybe this does also get fixed with the `ie >= 10`, not sure, tho!
