### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by stasoft91** [KitchenStories/vue-gallery-slideshow#16]
> node_modules/vue-gallery-slideshow/dist/js/vue-gallery-slideshow.js
>> const HEAD = document.head || document.getElementsByTagName('head')[0];
document is not defined

**Comment by headione** [comment]
> > node_modules/vue-gallery-slideshow/dist/js/vue-gallery-slideshow.js
> > > const HEAD = document.head || document.getElementsByTagName('head')[0];
> > > document is not defined

@stasoft91 This dependency is client-side only and dependent on `window.document`. Please wrap the component in a `<no-ssr>` element like shown below:

```
...
<img class="image" v-for="(image, i) in images" :src="image" :key="i" @click="index = i">
<no-ssr placeholder="loading...">
  <vgs :images="images" :index="index" @close="index = null" />
</no-ssr>
...
```

I hope this helps, I'll close this issue now.
