### ISSUE TITLE
this component can’t run in IE11 and safari5.1?

### ISSUE THREAD

**Issue by leeycode** [KitchenStories/vue-gallery-slideshow#2]

**Comment by headione** [comment]
That may be. I’ll check and fix this asap, thanks!

**Comment by jonathan-neugber** [comment]
Can confirm this as I am having the same issue right now.

It occurs because IE11 does not support shorthand functions like:

```javascript
{
  mounted() {},
  watch() {},
}
```

So it needs to be transpiled for ES5 support.

**Comment by headione** [comment]
Oh right, I forgot to add babel again after a rollup update. I’ll fix this asap when I’m back from my current roadtrip. Thanks for finding out!

**Comment by headione** [comment]
i just released a hotfix version 1.2.4 with included babel build. i would see this issue as fixed. let me know if problems still occur. cheers 🍻

**Comment by spiritinlife** [comment]
@headione This seems to be an issue again. If you see in the dist script there is a => use    https://github.com/KitchenStories/vue-gallery-slideshow/blob/caf6ad7739b953de2066c2b33e5de65d27d0b8a4/dist/js/vue-gallery-slideshow.js#L303 which is not es5 compatible.
