### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by phynos** [KitchenStories/vue-gallery-slideshow#21]
MY poor English obscured my meaning.
How full sceen in body when use single file compoent ?

**Comment by headione** [comment]
Hi, fullscreen mode is not supported yet but it would be a nice feature for later

**Comment by vesper8** [comment]
This is how I achieved "full screen"

```
.vgs .vgs__container {
  height: 100vh !important;
  width: 100vw !important;
  max-width: inherit !important;
  margin: 0 !important;
}
```
