### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by jericopulvera** [KitchenStories/vue-gallery-slideshow#3]

**Comment by iHazzam** [comment]
I've done the (opinionated) work to provide this on my fork. If @headione wants to integrate this I'd be happy to make a PR - but it doesn't have tests and I don't know enough Javascript to write them

**Comment by headione** [comment]
@iHazzam that sounds great! Please submit a pull request and I will have look at it :)

**Comment by headione** [comment]
thanks for your PR! I'll check, test and give you an update asap @iHazzam 🕺

**Comment by iHazzam** [comment]
Thanks, let me know if there's anything needs doing on my end - I'm not a JS developer so probably haven't followed standards etc. 
Cheers & thanks for a well written and enjoyably simple gallery!

**Comment by headione** [comment]
Hey, sorry I need to close this because I wanna keep VGS as image-only slideshow and as lightweight as possible.
