### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by ansidev** [KitchenStories/vue-gallery-slideshow#32]
**Problem:**

ERROR in ./node_modules/vue-gallery-slideshow/dist/js/vue-gallery-slideshow.js
Module not found: Error: Can't resolve 'vue-runtime-helpers' in 'node_modules\vue-gallery-slideshow\dist\js'

**Solution:**

Add dependency package `vue-runtime-helpers`.
You should update the documentation.

**Comment by headione** [comment]
Thanks for the report! This problem is solved with the new version v1.5.1 and `vue-runtime-helpers` is now added to the projects's bundle.
