### ISSUE TITLE
Update commit messages to show what versions added

### ISSUE THREAD

**Issue by iHazzam** [KitchenStories/vue-gallery-slideshow#7]
Unable to tell what the new version includes or fixes

would be helpful to have it added to readme or commit message

**Comment by headione** [comment]
Good point. Usally i'm using the CHANGELOG.md file for this. At the moment there's a problem with uploading to unpkg.com. Usually it will be deployed to unpkg.com after publishing the new version but this is not working at the moment :/ it falls always back to version 1.2.4 but the latest ist 1.2.9. I'll try to fix the implementation via CDN. I was trying to trigger a deploy to unpkg and this is why i forced some releases but obviously it didn't help. Sorry for that!
